# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ziBCr6honRS1StvGaWjIkMsZXi4bxae7
"""

import socket
import getpass
senha = "123456"
entrada = ""
while(entrada != senha):
    entrada = getpass.getpass("Digite a senha: ")
    if (entrada == senha):
        s = socket.socket()
        s.connect(("8.8.8.8", 53))
        ip_address = s.getsockname()[0]
        print ("Acesso autorizado. Endereco IP: "+ ip_address)
        s.close()
    else:
        print ("Senha incorreta, tente novamente: ")